ALTER TABLE medic_secure_humana
  ALTER COLUMN trabajador_rol TYPE NUMERIC(18,8),
  ALTER COLUMN urbapark TYPE NUMERIC(18,8),
  ALTER COLUMN prima TYPE NUMERIC(18,8),
  ALTER COLUMN ajuste TYPE NUMERIC(18,8),
  ALTER COLUMN assist TYPE NUMERIC(18,8),
  ALTER COLUMN seguro TYPE NUMERIC(18,8);
